# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='published',
        ),
    ]
