# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200524_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='status',
        ),
    ]
