# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200524_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='publish', max_length=250, unique_for_date='publish'),
        ),
    ]
